Doc improvements
camueller/SmartApplianceEnabler pull request #543
Opened 2023-07-11 20:57 UTC by starwarsfan

Hallo Axel,

vielen Dank für das coole Tool! Nachdem ich mich nun seit einer Weile mit dem SmartApplianceEnabler beschäftige (muss einem potentiellen Bug auf den Grund gehen), habe ich die letzten Tage verwendet, die gesamte deutsche Dokumentation hinsichtlich Einheitlichkeit und Typos zu überarbeiten. Damit das dennoch einigermassen übersichtlich bleibt und ggf. auch geändert/reverted werden kann, habe ich jede Datei einzeln committed. Die Changes sind hauptsächlich dieser Art:

- Typos und Satzbau korrigiert
- Sämtliche Code-Snippets vereinheitlicht:
  - Korrektes Syntax-Highlighting je nach Inhalt. Damit sind die Code-Fragmente bspw. direkt aus IntelliJ heraus ausführbar.
  - Überflüssige Prompts entfernt bzw. nur noch dort erhalten, wo sie für das Verständnis relevant sind
- Einige Ergänzungen bzw. Erweiterungen
- Ticket-Templates hinzugefügt

Ich hoffe, das ist so in Deinem Sinne. Je nachdem wie es meine Zeit erlaubt, würde ich auch noch die englische Doku durcharbeiten.

2023-07-12 09:55 UTC, camueller commented
Super! Vielen Dank für Deine Mühe. Ich werde den PR prüfen.

2023-07-12 16:47 UTC, starwarsfan commented
Cool, freut mich zu hören.

Noch etwas: Mit ea18a5e4 habe ich die Angabe bzgl. der maximal möglichen Geräte im SHM auf 23 geändert, weil das bei mir genau so ist.  Meine Anlage wurde im April montiert.

2023-07-12 18:07 UTC, camueller commented
> Noch etwas: Mit [ea18a5e](https://github.com/camueller/SmartApplianceEnabler/commit/ea18a5e47d7944f08a614f2db2631e7a77da5230) habe ich die Angabe bzgl. der maximal möglichen Geräte im SHM auf 23 geändert, weil das bei mir genau so ist. Meine Anlage wurde im April montiert.

Ich habe von mindestens 2 Usern gegenteiliges Feedback bekommen und auch von SMA selbst die Information, dass der "Hack", um 23 Geräte zu nutzen, nicht mehr funktioniert. Wie kann es da sein, dass Du 23 Geräte im Sunny Portal hast?

2023-07-12 18:29 UTC, starwarsfan commented
> Ich habe von mindestens 2 Usern gegenteiliges Feedback bekommen und auch von SMA selbst die Information, dass der "Hack", um 23 Geräte zu nutzen, nicht mehr funktioniert. Wie kann es da sein, dass Du 23 Geräte im Sunny Portal hast?

Oh, na das ist ja interessant. Ich habe überhaupt nichts gemacht ausser einfach im SAE drei Geräte einzurichten. Diese sind dann im SHM aufgetaucht und dort sehe ich die Meldung, dass ich noch entsprechend viele Geräte hinzufügen kann. 

Aber vielleicht sprechen wir auch von zwei verschiedenen Dingen denn ich war soeben nochmal bei mir auf dem Portal und habe das entsprechende Tooltip geöffnet. Das sieht so aus:

![image](https://github.com/camueller/SmartApplianceEnabler/assets/1954385/0adaa3e6-c963-4cf9-9a55-fb21012d3d9b)

Es wird also von zwölf steuerbaren Geräten und zwölf nicht steuerbaren Geräten gesprochen. Ist das evtl. etwas Neues?

2023-07-13 04:59 UTC, camueller commented
> Es wird also von zwölf steuerbaren Geräten und zwölf nicht steuerbaren Geräten gesprochen. Ist das evtl. etwas Neues?

Die SEMP-Geräte zählen zu den steuerbaren Geräten, auch wenn sie nicht gesteuert werden. Du wirst es nicht schaffen, mehr als 12 Geräte zum Sunny Portal hinzuzufügen (bis letztes Jahr ging es - habe selbst 23 Geräte konfiguriert). Insofern sollten wir in der Doku das auch so belassen.

2023-07-13 06:10 UTC, starwarsfan commented
> Die SEMP-Geräte zählen zu den steuerbaren Geräten, auch wenn sie nicht gesteuert werden.

Verstehe, alles klar. Habe es reverted und zum besseren Verständnis noch einen Hinweis wenig ergänzt.

2023-07-17 17:23 UTC, camueller requested changes
Respekt - Du hast sehr viel Mühe in die Korrektur der Text gesteckt. Ich hätte nie gedacht, dass das so viele Fehler drin sind. Ganz herzlichen Dank für Deine Arbeit!

2023-07-17 17:23 UTC, camueller commented on .github/ISSUE_TEMPLATE/bug_report.md
> +name: Bug report
Fast alle User sind im deutschsprachigen Raum und nciht alle können Englisch. Ich fände es gut, wenn die Templates neben den englischen Texten auch deutsche Texte beinhalten würden.

2023-07-17 17:23 UTC, camueller commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
Fast alle User sind im deutschsprachigen Raum und nciht alle können Englisch. Ich fände es gut, wenn die Templates neben den englischen Texten auch deutsche Texte beinhalten würden.

2023-07-17 17:23 UTC, camueller commented on doc/ConfigurationFiles_DE.md
> +<a name="log-konfiguration"></a>
Vielleicht auch in die ÜBerschrift selbst reinziehen, wie oben bei "Kopieren der Konfigurationsdateien zwischen Raspberry Pi und PC"? Oder oben auch nicht reinziehen - jedenfalls sollte es einheitlich sein :-)

2023-07-17 17:23 UTC, camueller commented on doc/Configuration_DE.md
> +Die Konfiguration erfolgt über das Web-Frontend des *Smart Appliance Enabler*. Dazu muss man im Web-Browser lediglich `http://raspi:8080` eingeben, wobei *raspi* durch den Hostnamen oder die IP-Adres
```suggestion
Die Konfiguration erfolgt über das Web-Frontend des *Smart Appliance Enabler*. Dazu muss man im Web-Browser lediglich `http://raspi:8080` eingeben, wobei *raspi* durch den Hostnamen oder die IP-Adresse des Raspberry Pi ersetzt wird. Es öffnet sich die Status-Seite mit dem Hinweis, dass noch keine Geräte konfiguriert sind.
```

2023-07-17 17:23 UTC, camueller commented on doc/Configuration_DE.md
> +Grundsätzlich gilt, dass Eingaben/Änderungen erst nach dem [Klicken der `Speichern` Schaltfläche](ConfigurationFiles_DE.md#speichern) gespeichert sind. Beim Wechsel auf ein andere Seite erfolgt eine
Warum soll der Bindestrich zwischen den Wörtern weg? Habe ich irgendeine Sprachereform verpasst ;-) ? Bezieht sich auch auf die nachfolgenden zwei Änderungen.

2023-07-17 17:23 UTC, camueller commented on doc/Contribute_DE.md
> +2. An den Dateien dieses "geforkten" Repositories kannst Du jetzt die eigentlichen Änderungen vornehmen oder neue Dateien hinzufügen
Manuelle Nummerierung nciht notwendig, Markdown zählt das automatisch hoch.

2023-07-17 17:23 UTC, camueller commented on doc/Contribute_DE.md
> +3. Erstelle einen "Pull Request", um damit die Übernahme Deiner Änderungen in das originale *Smart Appliance Enabler* Repository zu beantragen
Manuelle Nummerierung nicht notwendig, Markdown zählt das automatisch hoch.

2023-07-17 17:23 UTC, camueller commented on doc/Development_DE.md
> +Beim *Smart Appliance Enabler* handelt es sich um eine [Spring Boot](http://projects.spring.io/spring-boot) Anwendung mit einer [Angular](https://angular.io) Web-Anwendung.
```suggestion
Beim *Smart Appliance Enabler* handelt es sich um eine [Spring Boot](http://projects.spring.io/spring-boot)-Anwendung mit einer [Angular](https://angular.io)-Web-Anwendung. 
```

2023-07-17 17:23 UTC, camueller commented on doc/Development_DE.md
> +Als Automatisierungswerkzeug wird [Jenkins](https://www.jenkins.io/) eingesetzt, der aktuell aus Kostengründen auf **meinem 24x7-Server** läuft und nicht aus dem Internet erreichbar ist. Sobald diese
```suggestion
Als Automatisierungswerkzeug wird [Jenkins](https://www.jenkins.io/) eingesetzt, der aktuell aus Kostengründen auf **meinem 24x7-Server** läuft und nicht aus dem Internet erreichbar ist. Sobald dieser Änderungen am [*Smart Appliance Enabler*-Github-Repository](https://github.com/camueller/SmartApplianceEnabler) erkennt, started er die [Build-Pipeline](https://github.com/camueller/SmartApplianceEnabler/blob/master/Jenkinsfile). In der Pipeline wird zunächst das Java-Backend kompiliert und die zugehörigen Unit-Tests ausgeführt. Danach wird die Web-Anwendung gebaut und durch die zugehörigen Unit-Tests ebenfalls ausgeführt. Beides wird in einer `war`-Datei paketiert, welche von einer **Java-Runtime** als Web-Anwendung ausgeführt werden kann.
```

2023-07-17 17:23 UTC, camueller commented on doc/Development_DE.md
> +Angesichts dieser Probleme stoppe ich hier erstmal den Versuch, die automatische Installation zu testen.
```suggestion
Angesichts dieser Probleme stoppe ich hier erstmal den Versuch, die automatische Installation automatisiert zu testen.
```

2023-07-17 17:23 UTC, camueller commented on doc/Development_DE.md
> +2. Version in `pom.xml` erhöhen
Da muss man jedes Mal alle Nummern ändern, wenn man etwas einfügt. Deshalb ist es besser, immer "1" zu verwenden und Markdwon kümmert sich um die korrekte Nummerierung.

2023-07-17 17:23 UTC, camueller commented on doc/Development_DE.md
> +Zum Einschalten eines Gerätes eignet sich folgender Befehl, wobei der Parameter `RecommendedPowerConsumption` nur für Wallboxen relevant ist:
```suggestion
Zum Einschalten eines Gerätes eignet sich folgender Befehl, wobei der Parameter `RecommendedPowerConsumption` nur für Geräte mit variabler Leistungsaufnahme (z.B. Wallboxen) relevant ist:
```

2023-07-17 17:23 UTC, camueller commented on doc/Docker_DE.md
> +**Achtung:** Wenn der Container schon lange läuft, kann die Log-Ausgabe sehr lang sein! Daher empfiehlt sich an dieser Stelle die Verwendung der Optionen `--tail` oder `--since`, siehe [Dokumentation
Sehr guter Hinweis!

2023-07-17 17:23 UTC, camueller commented on doc/Logging_DE.md
> +Der *Smart Appliance Enabler* loggt Fehler mit dem Log-Level `ERROR`. d.h. dieses "Wort" kann man als Such-Kriterium verwenden.
```suggestion
Der *Smart Appliance Enabler* loggt Fehler mit dem Log-Level `ERROR`, d.h. dieses "Wort" kann man als Such-Kriterium verwenden.
```

2023-07-17 17:23 UTC, camueller commented on doc/MQTT_DE.md
> +Standardmäßig haben alle Ereignisse folgenden `Inhalt`:
```suggestion
Standardmäßig haben alle Ereignisse folgenden Inhalt: 
```

2023-07-17 17:23 UTC, camueller commented on doc/Settings_DE.md
> +Die Feiertage werden aus der Datei `Holidays-JJJJ.txt` gelesen, wobei JJJJ durch die Jahreszahl ersetzt wird, d.h. die Feiertage für 2023 finden sich in der Datei `Holidays-2023.txt`.
Sonst passt es nicht zum nachfolgend gezeigten Inhalt der Datei ...
```suggestion
Die Feiertage werden aus der Datei `Holidays-JJJJ.txt` gelesen, wobei JJJJ durch die Jahreszahl ersetzt wird, d.h. die Feiertage für 2017 finden sich in der Datei `Holidays-2017.txt`. 
```

2023-07-17 17:23 UTC, camueller commented on doc/Settings_DE.md
> +<a name="user-content-modbus"></a>
Warum hier mit Prefix `user-content-`? Bei den anderen `a`--Tags ist das nicht so ...

2023-07-18 20:20 UTC, starwarsfan commented
Hallo Axel

> Respekt - Du hast sehr viel Mühe in die Korrektur der Text gesteckt. Ich hätte nie gedacht, dass das so viele Fehler drin sind. Ganz herzlichen Dank für Deine Arbeit!

Joa, hatte einfach mal angefangen und dann lief es... ;-)

Schau' ich mir auf jeden Fall alles an. Bin nur gerade mit der Familie ein paar Tage in den Ferien, wird also nicht vor dem Wochenende.

2023-07-23 17:48 UTC, starwarsfan commented on .github/ISSUE_TEMPLATE/bug_report.md
> +name: Bug report
Deutsches Template hinzugefügt. Allerdings bin ich mir nicht sicher, ob das von Github so unterstützt wird. Aber das werden wir sehe, ggf. kann dann auch einfach das englische Template gelöscht werden.

2023-07-23 17:49 UTC, starwarsfan commented on .github/ISSUE_TEMPLATE/feature_request.md
> +name: Feature request
Deutsches Template hinzugefügt. Allerdings bin ich mir nicht sicher, ob das von Github so unterstützt wird. Aber das werden wir sehe, ggf. kann dann auch einfach das englische Template gelöscht werden.

2023-07-23 17:50 UTC, starwarsfan commented on doc/ConfigurationFiles_DE.md
> +<a name="log-konfiguration"></a>
Naja, ich habe mit diesen Changes einfach nur die Fehler gefixt, welche mir IntelliJ in der Markup-Syntax zeigt. Das strukturell einheitlich zu machen, ist dann nochmal eine andere Hausnummer..

2023-07-23 17:52 UTC, starwarsfan commented on doc/Settings_DE.md
> +<a name="user-content-modbus"></a>
Das kann ich Dir auch nicht sagen, ich habe rückwärts nach Referenzen gesucht und nur "user-content-modbus" gefunden, nicht aber "modbus". Aber kann man natürlich auch andersherum machen.

2023-07-23 18:00 UTC, starwarsfan commented on doc/Contribute_DE.md
> +2. An den Dateien dieses "geforkten" Repositories kannst Du jetzt die eigentlichen Änderungen vornehmen oder neue Dateien hinzufügen
Ja, das ist wahr. Da gibt's auch einen Feature-Request bei Jetbrains dazu: https://youtrack.jetbrains.com/issue/IDEA-278059/Numbered-Lists-in-Markdown-Syntax. Ich reverte das.

2023-07-23 18:05 UTC, starwarsfan commented on doc/Contribute_DE.md
> +3. Erstelle einen "Pull Request", um damit die Übernahme Deiner Änderungen in das originale *Smart Appliance Enabler* Repository zu beantragen
Reverted

2023-07-23 18:08 UTC, starwarsfan commented on doc/Development_DE.md
> +2. Version in `pom.xml` erhöhen
Reverted

2023-07-23 18:31 UTC, starwarsfan commented on doc/ConfigurationFiles_DE.md
> +<a name="log-konfiguration"></a>
Erledigt.

2023-07-23 18:35 UTC, starwarsfan commented on doc/Settings_DE.md
> +<a name="user-content-modbus"></a>
Fixed

2023-07-23 18:39 UTC, starwarsfan commented on doc/Configuration_DE.md
> +Grundsätzlich gilt, dass Eingaben/Änderungen erst nach dem [Klicken der `Speichern` Schaltfläche](ConfigurationFiles_DE.md#speichern) gespeichert sind. Beim Wechsel auf ein andere Seite erfolgt eine
Stimmt, besser so wie vorher. Reverted.

2023-08-03 18:51 UTC, starwarsfan commented
Hoi Alex, vermisst Du noch etwas? Hab' ich etwas vergessen oder bist Du einfach noch nicht dazu gekommen, die Korrekturen anzuschauen?

2023-08-04 04:02 UTC, camueller commented
Ich habe noch keine Zeit gehabt. Hoffe, dass ich in den nächsten Tage dazu komme ...

2023-08-05 04:07 UTC, merged

2023-08-05 04:07 UTC, camueller commented
Sieht gut aus mit den Änderungen!